#!/bin/sh

source /usr/share/pgadmin4/bin/activate

# Get the session timeout from the pgAdmin config. We'll use this (in seconds)
# to define the Gunicorn worker timeout
TIMEOUT=$(python3 -c 'from pgadmin4 import config; print(config.SESSION_EXPIRATION_TIME * 60 * 60 * 24)')

# NOTE: currently pgadmin can run only with 1 worker due to sessions implementation
# Using --threads to have multi-threaded single-process worker

if [ -z ${PGADMIN_ENABLE_TLS} ]; then
    : ${PGADMIN_LISTEN_PORT:-80}
    PGADMIN_CERT_AND_KEY=
else
    : ${PGADMIN_LISTEN_PORT:=443}
    PGADMIN_CERT_AND_KEY="--keyfile /certs/server.key --certfile /certs/server.cert"
fi
exec gunicorn --timeout ${TIMEOUT} --bind ${PGADMIN_LISTEN_ADDRESS:-[::]}:${PGADMIN_LISTEN_PORT} ${PGADMIN_CERT_AND_KEY} -w 1 --threads ${GUNICORN_THREADS:-25} --access-logfile ${GUNICORN_ACCESS_LOGFILE:--} $tls_args pgadmin4.pgAdmin4:app
